# I wasn't sure where to put this...
# We can delete it from here if we want to move it to docs-builder.
apm: 'APM'
apm-dotnet-agent: 'APM .NET Agent'
apm-android-agent: 'APM Android Agent'
apm-attacher: 'APM Attacher'
apm-aws-lambda-extension: 'APM AWS Lambda extension'
apm-go-agent: 'APM Go Agent'
apm-i-os-agent: 'APM iOS Agent'
apm-java-agent: 'APM Java Agent'
apm-node-agent: 'APM Node.js Agent'
apm-php-agent: 'APM PHP Agent'
apm-python-agent: 'APM Python Agent'
apm-ruby-agent: 'APM Ruby Agent'
apm-rum-agent: 'APM RUM Agent'
beats-logging-plugin: 'Beats Logging plugin'
cloud-control-ecctl: 'Cloud Control ECCTL'
cloud-enterprise: 'Cloud Enterprise'
cloud-hosted: 'Cloud Hosted'
cloud-kubernetes: 'Cloud Kubernetes'
cloud-native-ingest: 'Cloud Native Ingest'
cloud-serverless: 'Cloud Serverless'
cloud-terraform: 'Cloud Terraform'
ecs-logging: 'ECS Logging'
ecs-logging-dotnet: 'ECS Logging .NET'
ecs-logging-go-logrus: 'ECS Logging Go Logrus'
ecs-logging-go-zap: 'ECS Logging Go Zap'
ecs-logging-go-zerolog: 'ECS Logging Go Zerolog'
ecs-logging-java: 'ECS Logging Java'
ecs-logging-node: 'ECS Logging Node.js'
ecs-logging-php: 'ECS Logging PHP'
ecs-logging-python: 'ECS Logging Python'
ecs-logging-ruby: 'ECS Logging Ruby'
elastic-agent: 'Elastic Agent'
ecs: 'Elastic Common Schema (ECS)'
elastic-products-platform: 'Elastic Products platform'
elastic-stack: 'Elastic Stack'
elasticsearch: 'Elasticsearch'
elasticsearch-dotnet-client: 'Elasticsearch .NET Client'
elasticsearch-apache-hadoop: 'Elasticsearch Apache Hadoop'
elasticsearch-cloud-hosted-heroku: 'Elasticsearch Cloud Hosted Heroku'
elasticsearch-community-clients: 'Elasticsearch community clients'
elasticsearch-curator: 'Elasticsearch Curator'
elasticsearch-eland-python-client: 'Elasticsearch Eland Python Client'
elasticsearch-go-client: 'Elasticsearch Go Client'
elasticsearch-groovy-client: 'Elasticsearch Groovy Client'
elasticsearch-java-client: 'Elasticsearch Java Client'
elasticsearch-java-script-client: 'Elasticsearch JavaScript Client'
elasticsearch-painless-scripting-language: 'Elasticsearch Painless scripting language'
elasticsearch-perl-client: 'Elasticsearch Perl Client'
elasticsearch-php-client: 'Elasticsearch PHP Client'
elasticsearch-plugins: 'Elasticsearch plugins'
elasticsearch-python-client: 'Elasticsearch Python Client'
elasticsearch-resiliency-status: 'Elasticsearch Resiliency Status'
elasticsearch-ruby-client: 'Elasticsearch Ruby Client'
elasticsearch-rust-client: 'Elasticsearch Rust Client'
fleet: 'Fleet'
ingest: 'Ingest'
integrations: 'Integrations'
kibana: 'Kibana'
logstash: 'Logstash'
machine-learning: 'Machine Learning'
observability: 'Observability'
reference-architectures: 'Reference Architectures'
search-ui: 'Search UI'
security: 'Security'