name: Label Community Issues

on:
  issues:
    types: [opened]

jobs:
  label-community-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Add community label
        if: ${{ github.event.issue.author_association != 'MEMBER' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueAuthor = '${{ github.event.issue.user.login }}';
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['community']
            });
            
            console.log(`Added "community" label to issue by ${issueAuthor}`);
